servicemesh_namespace: "ossm-system"
servicemesh_subscriptions:
  - { operator: "elasticsearch-operator", namespace: "openshift-operators-redhat" }
  - { operator: "jaeger-product", namespace: "openshift-operators" }
  - { operator: "kiali-ossm", namespace: "openshift-operators" }
  - { operator: "servicemeshoperator", namespace: "openshift-operators" }
