# RHPDS: CloudForms API URL
rhpds_api_url: "https://rhpds.redhat.com"
rhpds_service_name: "OpenShift Workshop 4.5"
rhpds_service_catalogue: "/api/service_catalogs/30000000000074/service_templates/30000000000675"

# OPENTLC: CloudForms API URL
opentlc_api_url: "https://labs.opentlc.com"
opentlc_service_name: "OpenShift 4 Installation Lab"
opentlc_service_catalogue: "/api/service_catalogs/20000000000040/service_templates/20000000000619"

# OpenShift Version 
# openshift_version: "4.3.13"
# https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.3.13.tar.gz
# https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.3.13.tar.gz
openshift_latest_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/"
openshift_client_pattern: "(openshift-client-linux-\\d{1,3}.\\d{1,3}.\\d{1,3}.tar.gz)"
openshift_install_pattern: "(openshift-install-linux-\\d{1,3}.\\d{1,3}.\\d{1,3}.tar.gz)"
# openshift_install: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-{{ openshift_version }}.tar.gz", filename: "openshift-install.tar.gz" }
# openshift_client: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-{{ openshift_version }}.tar.gz", filename: "openshift-client.tar.gz" }
# openshift_version: "4.5.0-0.nightly-2020-04-15-094549" # https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.5/openshift-install-linux-4.5.0-0.nightly-2020-04-15-094549.tar.gz
# openshift_install: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.5/openshift-install-linux-{{ openshift_version }}.tar.gz", filename: "openshift-install.tar.gz" }
# openshift_client: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest-4.5/openshift-client-linux-{{ openshift_version }}.tar.gz", filename: "openshift-client.tar.gz" }

# AWS Information
aws_region: "us-east-2"
aws_client: { url: "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip", filename: "awscli-bundle.zip" }

# (Optional) If you want to automatically open the browser
#            provide the location of your browser
google_chrome: "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome"

# Region used to provisioning: na_gpte, emea_gpte, apac_gpte
cloudforms_region: na2_gpte
