# - name: "Installing Python PIP"
#   yum: name=python-pip state=latest

# - name: "Library for Python: docker-py"
#   command: pip install docker-py

- name: "Docker CE: Adding Repository"
  get_url: url=https://download.docker.com/linux/centos/docker-ce.repo
           dest=/etc/yum.repos.d

- name: Fixing a problem in RHEL, unable to replace variable $releaseserver 
  replace: path=/etc/yum.repos.d/docker-ce.repo regexp="[$]releasever" replace="7"

- name: Removing Original Docker
  yum: name=[docker,docker-ce,docker-common,docker-client,containerd.io] state=absent

- name: Installing ContainerD.IO 
  yum: name=https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm
       disable_gpg_check=true state=present

- name: Installing Docker CE
  yum: name=docker-ce state=present

- name: Starting Docker CE Service
  service: name=docker state=started enabled=yes

- name: "If docker credentials are provided, docker login: docker_registry, docker_username, docker_password"
#  docker_login: registry={{ docker_registry }} username={{ docker_username }} password={{ docker_password }}
  command: docker login --username={{ docker_username }} --password {{ docker_password }} {{ docker_registry }}
  when: docker_registry is defined and docker_registry is not none and docker_username is defined and docker_username is not none and docker_password is defined and docker_password is not none
