- name: "Fetching Custom Attributes{{ ':' }} {{ service_selected }}"
  uri: url={{ service_selected }}?attributes=custom_attributes method=GET status_code=200
      headers={"Content-type":"application/json","Accept":"application/json","X-Auth-Token":"{{ authentication_token }}"}
  register: custom_attributes

- name: Fetching OpenShift API (Environment Info 1)
  set_fact: openshift_api={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 1'].value")|first|regex_replace("^Openshift API for command line 'oc' client[:] ", "") }}

# - debug: var=openshift_api

- name: Fetching SSH Access information (Environment Info 10)
  set_fact: ssh_host_user_and_password={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 10'].value")|first|regex_replace("^Make sure you use the username \'", "") }}

# - debug: var=ssh_host_user_and_password 

- set_fact: target_host_user="{{ ssh_host_user_and_password | regex_replace("\`(.*)$", "") | regex_replace("\'(.*)$", "") }}"
- set_fact: target_host_password="{{ ssh_host_user_and_password | regex_replace("^(.*)\'[ ]and[ ]the[ ]password[ ]\'", "") | regex_replace("\'[ ]when[ ]prompted[.]$", "") }}"

- name: SSH Target Host (Environment Info 9)
  set_fact: target_host_name={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 9'].value")|first| regex_replace("^(.*)[@]", "") }}

# - debug: var=target_host_name

- name: Fetching OpenShift user and password (Environment Info 5)
  set_fact: openshift_user_password={{ custom_attributes|json_query("json.custom_attributes[?name=='Environment Info 5'].value")|first|regex_replace("^User \`", "") }}

- set_fact: openshift_user="{{ openshift_user_password | regex_replace("\`(.*)$", "") }}"
- set_fact: openshift_password="{{ openshift_user_password | regex_replace("^(.*)\`[ ]with[ ]password[ ]\`", "") | regex_replace("\`[ ]is[ ]cluster[ ]admin[.]$", "")}}"
