- name: Retrieving Service URL
  uri: url={{ cloudforms_api_url }}/api/services method=GET status_code=200
       validate_certs=False
       headers={"Content-type":"application/json","Accept":"application/json","X-Auth-Token":"{{ authentication_token }}"}
  register: list_services

- name: "Check if there are any available services"
  fail: msg="There are no available services"
  when: list_services.json.subcount == 0  

- name: "Service Selected{{ ':' }} {{ list_services.json.resources[0].href }}"
  set_fact: service_selected="{{ list_services.json.resources[0].href }}"  