- name: "Creating directory: /root/cluster-{{ guid }}"
  file: path=/root/cluster-{{ guid }} state=directory
  tags: [ bastion ]

- name: Delete previously created Public and Private Keys
  file: path=/root/.ssh/{{ item }} state=absent
  loop:
      - cluster-{{ guid }}-key
      - cluster-{{ guid }}-key.pub
  ignore_errors: True

- name: "Generating SSH Public and Private Keys"
  command: "ssh-keygen -b 4096 -t rsa -f /root/.ssh/cluster-{{ guid }}-key -q -N \"\""
  tags: [ bastion, openshift_install ]

- name: "Creating a environment variables on /root/.bashrc"
  lineinfile: path=/root/.bashrc insertafter=EOF line="export {{ item }}"
  loop: 
        - "GUID={{ guid }}"
        - "KUBECONFIG=/root/cluster-{{ guid }}/auth/kubeconfig"
  tags: [ bastion, openshift_install ]

- name: Reading the contents of the Pull Secret File
  set_fact: openshift_pull_secret="{{ lookup('file', '{{ openshift_pull_secret_file }}') }}"
  tags: [ openshift_install, openshift_install_install_config ]

- name: Reading the contents of the public key file
  slurp: src=/root/.ssh/cluster-{{ guid }}-key.pub
  register: public_key
  tags: [ openshift_install, openshift_install_install_config ]

- name: "OpenShift Install: Generating Config File"
  template: src=install-config.yaml.j2 dest=/root/cluster-{{ guid }}/install-config.yaml
  tags: [ aws, openshift_install, openshift_install_install_config ]

- name: Inserting public key into /root/.ssh/authorized_keys
  copy: dest=/root/.ssh/authorized_keys content={{ hostvars['localhost']['public_key'] }}
  tags: [ bastion ]

- name: Installing all needed packages for Bastion
  dnf: name=screen state=present
  tags: [ bastion ]

- name: Looking for available clients
  uri: url={{ openshift_latest_url }} return_content=True
  register: available_content

- name: Fetching the latest version (OpenShift Client)
  set_fact: client_filename={{ available_content.content | regex_search(openshift_client_pattern) }}

- name: Fetching the latest version (OpenShift Install)
  set_fact: install_filename={{ available_content.content | regex_search(openshift_install_pattern) }}

- name: Deleting any existing file
  file: path=/tmp/{{ item }} state=absent
  loop: ["{{ client_filename }}", "{{ install_filename }}","{{ aws_client.filename }}","/tmp/awscli-bundle"]

- name: "Downloading Client: {{ client_filename }}"
  uri: url={{ openshift_latest_url }}{{ client_filename }} dest=/tmp/{{ client_filename }} validate_certs=False

- name: "Downloading Install: {{ install_filename }}"
  uri: url={{ openshift_latest_url }}{{ install_filename }} dest=/tmp/{{ install_filename }} validate_certs=False

- name: "Downloading AWS Client: {{ aws_client.filename }}"
  uri: url={{ aws_client.url }} dest=/tmp/{{ aws_client.filename }} validate_certs=False

- name: "Unarchiving files"
  unarchive: src=/tmp/{{ item }} dest=/tmp/ remote_src=True
  loop: ["{{ client_filename }}","{{ install_filename }}","{{ aws_client.filename }}"]

- name: "Move files: oc, kubectl, openshift-install to /usr/bin"
  copy: src=/tmp/{{ item }} dest=/usr/bin mode=755 remote_src=True
  loop: ["oc","kubectl","openshift-install"]

- name: "Setup Bash completion for the OpenShift command line utility"
  command: oc completion bash
  register: oc_completion_bash
  tags: [ bash_completion ]

- name: "Insert the content from <oc completion bash> into /etc/bash_completion.d/openshift"
  lineinfile: path=/etc/bash_completion.d/openshift insertafter=EOF line={{ oc_completion_bash.stdout }} create=true
  tags: [ bash_completion ]

- name: "AWS: Installing Client" 
  command: /tmp/awscli-bundle/install -i /usr/local/aws -b /bin/aws
  tags: [ aws ]

- name: "AWS: Creating Client configuration directory: /root/.aws"
  file: path=/root/.aws state=directory
  tags: [ aws ]

- name: "AWS: Generating AWS Client configuration: /root/.aws/credentials"
  template: src=aws_config.j2 dest=/root/.aws/credentials force=True
  tags: [ aws ]

- name: Cleaning
  file: path=/tmp/{{ item }} state=absent
  loop:
        - oc
        - kubectl
        - openshift-install
        - awscli-bundle
        - "{{ aws_client.filename }}"
        - "{{ client_filename }}"
        - "{{ install_filename }}"
  tags: [clean, openshift_install, openshift_client, aws ]

- name: Generating install_openshift.sh script
  template: src=install_openshift.sh.j2 dest=/root/install_openshift.sh mode=a+x
  tags: [ openshift_install ]

- name: Running openshift-install in Background
  command: screen -dm bash -c '/root/install_openshift.sh'
  tags: [ openshift_install ]

- debug: msg="openshift-install is running in background. ssh bastion and type{{ ':' }} screen -x"
